<?php
define('_DB_SERVER_', '10.0.0.51');
define('_DB_NAME_', 'aixmile');
define('_DB_USER_', 'aixmile');
define('_DB_PASSWD_', '123456');
define('_DB_PREFIX_', 'mb_');
define('_MYSQL_ENGINE_', 'MyISAM');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'GEwV1N7jotUEE0GAXXmRPdEbwtvrt20MeMrRsx0SUAz1O3Z5HLDDeh7E');
define('_COOKIE_IV_', 'onxCKZye');
define('_PS_CREATION_DATE_', '2019-04-03');
define('_PS_VERSION_', '1.5.2.0');
define('_MB_VERSION_', '3.1.3.3');
define('_RIJNDAEL_KEY_', 'VD7hwN8Xir5x3LzsNJndE9GggayaYhYt');
define('_RIJNDAEL_IV_', '+Lrf380mKTZma/RvxLuckw==');
